### ISSUE TITLE
Server node version too old for new ghost.

### ISSUE THREAD

**Issue by craig-mulligan** [resin-io/resin-blog#22]
I'm trying to update to the latest version of ghost but our production server is on node `0.10.40`

```
ubuntu@ip-10-218-178-164:/var/www/resin-blog-stage$ npm i
npm WARN engine ghost@0.11.4: wanted: {"node":"^4.2.0 || ^6.9.0"} (current: {"node":"0.10.40","npm":"1.4.28"})

> ghost@0.11.4 preinstall /var/www/resin-blog-stage/node_modules/ghost
> node core/server/utils/npm/preinstall.js

ERROR: Unsupported version of Node
Ghost supports LTS Node versions: ^4.2.0 || ^6.9.0
You are currently using version: 0.10.40
This check can be overridden, see http://support.ghost.org/supported-node-versions/ for more info

npm ERR! ghost@0.11.4 preinstall: `node core/server/utils/npm/preinstall.js`
npm ERR! Exit status 231
npm ERR! 
npm ERR! Failed at the ghost@0.11.4 preinstall script.
npm ERR! This is most likely a problem with the ghost package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node core/server/utils/npm/preinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ghost
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-36-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! cwd /var/www/resin-blog-stage
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

@brownjohnf How far off do you think containerising the services on this server are? If it's soon I think we should push these blog updates back.

**Comment by brownjohnf** [comment]
@craig-mulligan we should probably hold off on the server updates. Plus, since we only have the one server, it's going to be a mess to do the upgrade. If we wanted them right now, I'd say we should instead install docker on the server and run the components in containers.

**Comment by craig-mulligan** [comment]
I hear you. Do you have a rough eta for when resin-in-resin stuff would be ready for this? I'd prefer not set up an interim solution unless it's totally necessary.

**Comment by craig-mulligan** [comment]
Hey @brownjohnf how's https://github.com/resin-io/resin-lb going? Do you have an eta on when it'll be ready for some testing? I'm wondering if I should roll back the ghost version to push out updates or wait for resin-in-resin?

**Comment by brownjohnf** [comment]
@craig-mulligan It's basically production-ready, I believe. You can view the demo I've got running here: https://www.marketing.jack.resinplayground.io/. The link to the blog works, and the docs subdomain should work. I think once we get all the pieces ported to Docker we should be good to go. I'll share the resin apps with you that are running everything.

**Comment by brownjohnf** [comment]
Oh, and the other thing is getting EFS and an RDS database set up, so we can persist data across hosts.

**Comment by craig-mulligan** [comment]
Yass!!! Amazing, so hyped about this! :1st_place_medal: Yea still some open questions around how to share data + do backups. 

For the current blog instance, are you just pushing a ghost image from dockerhub?

**Comment by brownjohnf** [comment]
No, it's our codebase, tweaked to get working, and running without our data. Once I set up the DB and EFS I'll migrate everything across and it should populate properly.

**Comment by brownjohnf** [comment]
@craig-mulligan I'm really close to making the move. The remaining issues are mentioned in my resin-on-resin PR. All the EFS/RDS stuff is working, and migrations appear to work. Which version of Node would be ideal to run on?

**Comment by brownjohnf** [comment]
Closing this, since we're solving it by migrating to resin-on-resin.
